import { ScrollArea } from "@/components/ui/scroll-area";
import SelectOnboarding from "@/components/ui/select-onboarding";
import Navbar from "@/components/ui/navbar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Onboarding | Eurofarma",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  }
};
 export default function Onboarding() {
   return (
      <main className="flex flex-row">
      <Navbar/>
      <div className="p-4 w-[100%]">
        <SelectOnboarding/>
      </div>
      </main>
   )
 }
 