import SelectOnboarding from "@/components/ui/select-onboarding";
import Sidebar from "@/components/ui/sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Onboarding | Eurofarma",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  }
};
 export default function Onboarding() {
   return (
      <main className="flex flex-row">
      <Sidebar/>
      <div className="p-4 w-[15rem]">
        <SelectOnboarding/>
      </div>
      </main>
   )
 }
 