import ChatComponent from "@/components/ui/chat-component";
import Navbar from "@/components/ui/navbar";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Chatbot | Eurofarma",
    description: "Generated by create next app",
    icons: {
      icon: "/icon.png",
    }
  };
  
export default function Chatbot() {
    return (
        <main className="flex flex-col">
            <Navbar/>
            <div className="flex justify-center items-center mt-[5rem]">
                <ChatComponent/>
            </div>
        </main>
    )
}