import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Ubuntu } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

export const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: '--font-ubuntu'
})
export const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500","600","700"],
  variable: '--font-space-grotesk'
})
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${ubuntu.variable} ${space_grotesk.variable}`}>{children}</body>
    </html>
  );
}
