import Ia from "@/components/ui/ia";
import Sidebar from "@/components/ui/sidebar";
import { Metadata } from "next";
export const metadata: Metadata = {
    title: "IA | Eurofarma",
    description: "Generated by create next app",
    icons: {
      icon: "/icon.png",
    }
  };
export default function IaPage() {
    return (
        <main className="flex flex-row">
        <Sidebar/>
        <Ia/>
        </main>
    )
}